### ISSUE TITLE
Placement of Gitea Configuration 

### ISSUE THREAD

**Issue by r7l** [nemunaire/gentoo-overlay#1]
It seems you will take over the Gitea package in Gentoo. Is there a reason why the configuration needs to be in `/var/lib/gitea/conf` and not something like `/etc/gitea`?

Even Gitea Docs mention it to be there when installing from distribution:

> When installing from a distribution, this will typically be found at /etc/gitea/conf/app.ini

As in: https://docs.gitea.io/en-us/config-cheat-sheet/

I don't think we would need this *conf* part at all when placing it in `/etc/gitea` but most of the packages in Portage would handle configuration in a similar way or at least add symlinks from other places.

**Comment by nemunaire** [comment]
Hi @r7l!
Thank you for taking the time to report us that.

In fact, we are in the process of taking ownership on the package, we know the ebuild really needed cleaning, but as it was already difficult to have our package merged, we had preferred in a first time be minimal, but time passes and nothing move, so here it is. It'll be added to the PR by the end of the day.
